//! Tests for the resource safeguards.
//!
//! Every fixture here is generated by the test itself into a scratch
//! directory and removed on drop. Nothing binary is committed, and nothing
//! survives a run — a hostile file is not something to leave lying around,
//! and a fixture nobody can regenerate is a fixture nobody can trust.
//!
//! ## What these tests assert, and why it matters
//!
//! The trap in a safeguard suite is asserting that "something failed". A
//! test written that way passes against a completely broken importer, and
//! against one that refuses every file. So each test here asserts on:
//!
//! - the SPECIFIC error variant, and
//! - the NAME of the part that caused it, and where the criterion is about
//!   partial state, that the state really was discarded (sheet count, row
//!   count) rather than merely that an `Err` came back.

use super::*;
use std::io::Write;
use std::path::PathBuf;

/// Fixtures live under `benchdata/` in this clone, as the agent guide
/// requires, and are removed when the test ends.
struct Fixtures(PathBuf);

impl Fixtures {
    fn new(tag: &str) -> Self {
        let uniq = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        // Walk up from the crate directory to the workspace root so the
        // fixtures land in `benchdata/` regardless of where cargo is run.
        let root = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .and_then(|p| p.parent())
            .map(PathBuf::from)
            .unwrap_or_else(|| PathBuf::from("."));
        let d = root
            .join("benchdata")
            .join(format!("safeguard-{tag}-{uniq}"));
        std::fs::create_dir_all(&d).expect("create fixture dir");
        Self(d)
    }

    fn path(&self, name: &str) -> PathBuf {
        self.0.join(name)
    }
}

impl Drop for Fixtures {
    fn drop(&mut self) {
        // Only this test's own directory — peers may be running.
        let _ = std::fs::remove_dir_all(&self.0);
    }
}

/// Build a zip from `(name, contents)` pairs, stored uncompressed or
/// deflated as asked.
fn build_zip(path: &std::path::Path, entries: &[(&str, &[u8])], deflate: bool) {
    let f = std::fs::File::create(path).expect("create zip");
    let mut w = zip::ZipWriter::new(f);
    let opts: zip::write::SimpleFileOptions = zip::write::SimpleFileOptions::default()
        .compression_method(if deflate {
            zip::CompressionMethod::Deflated
        } else {
            zip::CompressionMethod::Stored
        });
    for (name, body) in entries {
        w.start_file(*name, opts).expect("start entry");
        w.write_all(body).expect("write entry");
    }
    w.finish().expect("finish zip");
}

fn open(path: &std::path::Path) -> zip::ZipArchive<std::fs::File> {
    zip::ZipArchive::new(std::fs::File::open(path).expect("open")).expect("parse zip")
}

// ------------------------------------------------------------ zip bombs ---

#[test]
fn a_bomb_is_refused_before_anything_is_extracted() {
    // THE acceptance criterion. 32 MB of zeroes deflates to a few kilobytes,
    // which is well past the 200x ratio limit. The refusal must happen from
    // the central directory alone.
    let fx = Fixtures::new("bomb");
    let p = fx.path("bomb.xlsx");
    let payload = vec![0u8; 32 << 20];
    build_zip(&p, &[("xl/worksheets/sheet1.xml", &payload)], true);

    let compressed = std::fs::metadata(&p).expect("stat").len();
    assert!(
        compressed < 1 << 20,
        "fixture is not actually a bomb: {compressed} bytes compressed"
    );

    let mut zip = open(&p);
    let limits = Limits::with_bytes(u64::MAX, u64::MAX);
    let err = inspect_archive(&mut zip, "bomb.xlsx", &limits)
        .expect_err("a 32MB-from-a-few-KB archive must be refused");

    // Not merely "an error" — the bomb error, with the real numbers in it.
    let SafeguardError::ZipBomb {
        declared,
        compressed: c,
        ratio,
        ..
    } = &err
    else {
        panic!("expected ZipBomb, got {err:?}");
    };
    assert_eq!(
        *declared,
        32 << 20,
        "declared size must come from the header"
    );
    assert!(*c > 0, "compressed size must be measured, not assumed");
    assert!(
        *ratio > DEFAULT_MAX_EXPANSION_RATIO,
        "ratio {ratio} should exceed the {DEFAULT_MAX_EXPANSION_RATIO}x limit"
    );
    assert!(err.is_pre_extraction(), "must be refused before extraction");
    // The message has to be usable by a human, not just matchable by a test.
    let msg = err.to_string();
    assert!(msg.contains("before extraction"), "{msg}");
    assert!(msg.contains("decompression bomb"), "{msg}");
}

#[test]
fn a_real_spreadsheet_is_not_mistaken_for_a_bomb() {
    // The other half of the criterion, and the one a too-eager check breaks:
    // ordinary XML compresses well, and refusing it would make the feature
    // worse than useless. Repetitive-but-realistic sheet XML.
    let fx = Fixtures::new("legit");
    let p = fx.path("legit.xlsx");
    let mut body = String::from("<worksheet><sheetData>");
    for r in 1..=20_000 {
        body.push_str(&format!(
            "<row r=\"{r}\"><c r=\"A{r}\"><v>{r}</v></c><c r=\"B{r}\" t=\"s\"><v>{}</v></c></row>",
            r % 97
        ));
    }
    body.push_str("</sheetData></worksheet>");
    build_zip(&p, &[("xl/worksheets/sheet1.xml", body.as_bytes())], true);

    let mut zip = open(&p);
    let report = inspect_archive(
        &mut zip,
        "legit.xlsx",
        &Limits::with_bytes(u64::MAX, u64::MAX),
    )
    .expect("ordinary sheet XML must not be refused");
    assert!(
        report.declared_bytes > 1 << 20,
        "fixture too small to be a meaningful control: {}",
        report.declared_bytes
    );
    assert!(
        report.expansion_ratio() > 5,
        "control fixture must actually compress well ({}x), or it proves nothing",
        report.expansion_ratio()
    );
}

#[test]
fn a_tiny_high_ratio_archive_is_allowed() {
    // 300x on 200 bytes is harmless. Applying the ratio without an absolute
    // floor would refuse `[Content_Types].xml` in every real workbook.
    let fx = Fixtures::new("tiny");
    let p = fx.path("tiny.xlsx");
    build_zip(&p, &[("a.xml", &vec![b'x'; 60_000])], true);
    let mut zip = open(&p);
    let report = inspect_archive(
        &mut zip,
        "tiny.xlsx",
        &Limits::with_bytes(u64::MAX, u64::MAX),
    )
    .unwrap();
    assert!(
        report.expansion_ratio() > DEFAULT_MAX_EXPANSION_RATIO,
        "fixture must exceed the ratio to test the floor, got {}x",
        report.expansion_ratio()
    );
    assert!(
        report.declared_bytes < EXPANSION_FLOOR_BYTES,
        "fixture must be under the floor to test it"
    );
}

#[test]
fn an_archive_over_the_total_budget_is_refused_with_its_declared_size() {
    let fx = Fixtures::new("total");
    let p = fx.path("big.xlsx");
    build_zip(&p, &[("a.xml", &vec![b'x'; 100_000])], false);
    let mut zip = open(&p);
    let err = inspect_archive(&mut zip, "big.xlsx", &Limits::with_bytes(1 << 20, 50_000))
        .expect_err("100KB declared must not fit a 50KB budget");
    let SafeguardError::ArchiveTooLarge { declared, .. } = &err else {
        panic!("expected ArchiveTooLarge, got {err:?}");
    };
    assert_eq!(*declared, 100_000);
}

// -------------------------------------------------------- path traversal ---

#[test]
fn traversing_entry_names_are_refused() {
    // Every spelling an attacker reaches for. `safe_entry_path` returning
    // None is what stops the join from landing outside the target.
    for hostile in [
        "../evil.xml",
        "../../etc/passwd",
        "xl/../../evil.xml",
        "..\\evil.xml",
        "xl\\..\\..\\evil.xml",
        "/etc/passwd",
        "/absolute.xml",
        "C:/Windows/system32/evil.dll",
        "C:\\Windows\\evil.dll",
        "..",
        "",
    ] {
        assert!(
            safe_entry_path(hostile).is_none(),
            "{hostile:?} must be refused as an archive entry name"
        );
    }
}

#[test]
fn ordinary_ooxml_entry_names_survive() {
    // The check must not break the real package layout — including the
    // `_rels` directories and the bracketed content-types part.
    for ok in [
        "[Content_Types].xml",
        "_rels/.rels",
        "xl/workbook.xml",
        "xl/_rels/workbook.xml.rels",
        "xl/worksheets/sheet1.xml",
        "xl/tables/table1.xml",
        "docProps/app.xml",
        "./xl/styles.xml",
    ] {
        assert!(
            safe_entry_path(ok).is_some(),
            "{ok:?} is a legitimate OOXML part and must be accepted"
        );
    }
}

#[test]
fn extraction_paths_stay_under_the_target_directory() {
    // The property that matters is not "None was returned" but "the path
    // that WOULD have been written is inside the target".
    let target = std::path::Path::new("C:/tmp/target");
    assert_eq!(safe_extract_path(target, "../escape.xml"), None);
    let inside = safe_extract_path(target, "xl/worksheets/sheet1.xml").expect("legal part");
    assert!(
        inside.starts_with(target),
        "{} escaped {}",
        inside.display(),
        target.display()
    );
}

#[test]
fn an_archive_containing_a_traversing_entry_is_refused_by_name() {
    let fx = Fixtures::new("traverse");
    let p = fx.path("traverse.xlsx");
    build_zip(
        &p,
        &[("xl/workbook.xml", b"<x/>"), ("../evil.xml", b"pwn")],
        false,
    );
    let mut zip = open(&p);
    let err = inspect_archive(
        &mut zip,
        "traverse.xlsx",
        &Limits::with_bytes(u64::MAX, u64::MAX),
    )
    .expect_err("an archive with a traversing entry must be refused");
    let SafeguardError::UnsafeEntryPath { entry, .. } = &err else {
        panic!("expected UnsafeEntryPath, got {err:?}");
    };
    assert!(
        entry.contains(".."),
        "the offending name must be reported: {entry}"
    );
    assert!(err.is_pre_extraction());
}

// ------------------------------------------------------ entity expansion ---

/// The classic billion-laughs payload, in the form a spreadsheet part would
/// carry it.
const BILLION_LAUGHS: &[u8] = br#"<?xml version="1.0"?>
<!DOCTYPE lolz [
 <!ENTITY lol "lol">
 <!ENTITY lol1 "&lol;&lol;&lol;&lol;&lol;&lol;&lol;&lol;&lol;&lol;">
 <!ENTITY lol2 "&lol1;&lol1;&lol1;&lol1;&lol1;&lol1;&lol1;&lol1;&lol1;&lol1;">
 <!ENTITY lol3 "&lol2;&lol2;&lol2;&lol2;&lol2;&lol2;&lol2;&lol2;&lol2;&lol2;">
 <!ENTITY lol4 "&lol3;&lol3;&lol3;&lol3;&lol3;&lol3;&lol3;&lol3;&lol3;&lol3;">
]>
<workbook><sheets><sheet name="&lol4;" sheetId="1"/></sheets></workbook>"#;

#[test]
fn billion_laughs_is_refused_at_the_doctype() {
    // Refused at the DECLARATION, before any reference to it is seen — the
    // only point at which the cost is still zero.
    let err = scan_part(BILLION_LAUGHS, "evil.xlsx", "xl/workbook.xml", None, |_| {
        Ok(())
    })
    .expect_err("a document type definition must be refused");
    let SafeguardError::EntityDeclaration { part, .. } = &err else {
        panic!("expected EntityDeclaration, got {err:?}");
    };
    assert_eq!(part, "xl/workbook.xml", "the failing part must be named");
    assert_eq!(err.part(), Some("xl/workbook.xml"));
}

#[test]
fn entity_expansion_is_not_possible_in_this_quick_xml() {
    // PINNING A DEPENDENCY PROPERTY, as the issue requires.
    //
    // quick-xml does not resolve DTD-declared entities: it emits a
    // `GeneralRef` event and leaves the decision to the caller. That is what
    // makes billion-laughs structurally impossible here rather than merely
    // caught. A future version that started expanding them would make the
    // DocType refusal above the only thing between us and a 3 GB allocation,
    // and this test is what would notice.
    //
    // Fed the payload with the guard REMOVED, so it tests quick-xml, not us.
    let mut rd = xml_reader(BILLION_LAUGHS);
    let mut buf = Vec::new();
    let mut total_text = 0usize;
    let mut saw_doctype = false;
    let mut refs = 0usize;
    loop {
        match rd.read_event_into(&mut buf) {
            Ok(quick_xml::events::Event::Eof) => break,
            Ok(quick_xml::events::Event::DocType(_)) => saw_doctype = true,
            Ok(quick_xml::events::Event::GeneralRef(_)) => refs += 1,
            Ok(quick_xml::events::Event::Text(t)) => total_text += t.len(),
            Ok(_) => {}
            Err(_) => break,
        }
        buf.clear();
    }
    assert!(
        saw_doctype,
        "the DOCTYPE must be surfaced as an event we can refuse"
    );
    assert!(
        total_text < 10_000,
        "quick-xml expanded entities: {total_text} bytes of text from a {} byte document — \
         billion-laughs is live and the DocType refusal is now the ONLY defence",
        BILLION_LAUGHS.len()
    );
    let _ = refs;
}

#[test]
fn an_undefined_entity_reference_is_refused_by_name() {
    // The second half of the entity defence: even without a DOCTYPE, a
    // reference to something undefined must not be silently dropped.
    let xml = br#"<workbook><sheet name="&payload;"/></workbook>"#;
    let err = scan_part(xml, "f.xlsx", "xl/workbook.xml", None, |_| Ok(()))
        .expect_err("an undefined entity must be refused");
    let SafeguardError::UndefinedEntity { name, part, .. } = &err else {
        panic!("expected UndefinedEntity, got {err:?}");
    };
    assert_eq!(name, "payload", "the entity name must be reported");
    assert_eq!(part, "xl/workbook.xml");
}

#[test]
fn the_five_predefined_entities_still_work() {
    // Refusing these would corrupt every note and format code containing a
    // quote or an ampersand — the exact silent data loss this crate already
    // has a comment about in `parse_comments_part`.
    let xml = br#"<t>a &amp; b &lt; c &gt; d &quot;e&quot; &apos;f&apos; &#65;</t>"#;
    let mut refs = 0usize;
    scan_part(xml, "f.xlsx", "part", None, |ev| {
        if matches!(ev, quick_xml::events::Event::GeneralRef(_)) {
            refs += 1;
        }
        Ok(())
    })
    .expect("predefined entities and character references must be accepted");
    assert_eq!(
        refs, 8,
        "all seven entity references plus the character reference must arrive"
    );
}

#[test]
fn an_entity_hidden_in_an_attribute_value_is_refused() {
    // Attribute values produce no `GeneralRef` event — they are decoded only
    // on demand — so an entity payload written as an attribute bypassed the
    // event-level check entirely. That is the exact form billion-laughs
    // takes (`<sheet name="&lol4;"/>`), so it has to be caught by name too.
    let xml = br#"<workbook><sheet name="&lol4;" sheetId="1"/></workbook>"#;
    let err = scan_part(xml, "f.xlsx", "xl/workbook.xml", None, |_| Ok(()))
        .expect_err("an entity in an attribute value must be refused");
    let SafeguardError::UndefinedEntity { name, part, .. } = &err else {
        panic!("expected UndefinedEntity, got {err:?}");
    };
    assert_eq!(name, "lol4", "the entity name must be reported");
    assert_eq!(part, "xl/workbook.xml");
}

#[test]
fn predefined_entities_in_attribute_values_still_work() {
    // The control for the check above. A currency format code is written as
    // `formatCode="&quot;$&quot;#,##0.00"`, so refusing these would break
    // every real workbook with a quoted number format.
    let xml = br#"<numFmt formatCode="&quot;$&quot;#,##0.00" x="a &amp; b" c="&#65;"/>"#;
    scan_part(xml, "f.xlsx", "xl/styles.xml", None, |_| Ok(()))
        .expect("predefined entities in attributes are legitimate OOXML");
}

// ---------------------------------------------------------- malformed xml ---

#[test]
fn a_truncated_part_names_the_part_and_the_offset() {
    // The criterion: a specific error naming the part, never a silent short
    // read. This is the exact shape of the defect the issue calls out.
    let xml = b"<workbook><sheets><sheet name=\"One\"/><sheet name=\"Tw";
    let err = scan_part(xml, "cut.xlsx", "xl/workbook.xml", None, |_| Ok(()))
        .expect_err("a truncated part must not parse as a complete one");
    let SafeguardError::MalformedXml { part, offset, .. } = &err else {
        panic!("expected MalformedXml, got {err:?}");
    };
    assert_eq!(part, "xl/workbook.xml");
    assert!(
        *offset > 0,
        "the offset must locate the failure, not default to zero"
    );
    assert!(err.to_string().contains("malformed"), "{err}");
}

#[test]
fn a_mismatched_end_tag_is_an_error() {
    let err = scan_part(b"<a><b></c></a>", "f.xlsx", "part", None, |_| Ok(()))
        .expect_err("mismatched end tags must be refused");
    assert!(
        matches!(err, SafeguardError::MalformedXml { .. }),
        "{err:?}"
    );
}

#[test]
fn a_well_formed_part_scans_to_completion() {
    // The control. Without this, every test above passes against a scanner
    // that rejects everything.
    let mut names = Vec::new();
    scan_part(
        br#"<workbook><sheets><sheet name="One"/><sheet name="Two"/></sheets></workbook>"#,
        "ok.xlsx",
        "xl/workbook.xml",
        None,
        |ev| {
            if let quick_xml::events::Event::Empty(e) = ev {
                if let Some(a) = e.attributes().flatten().find(|a| a.key.as_ref() == b"name") {
                    names.push(String::from_utf8_lossy(&a.value).into_owned());
                }
            }
            Ok(())
        },
    )
    .expect("well-formed XML must scan cleanly");
    assert_eq!(names, vec!["One", "Two"]);
}

// ------------------------------------------------- fuzz / property tests ---

/// A tiny deterministic PRNG, so a failure is reproducible from the seed
/// printed in the assertion message. `rand` is not a dependency of this
/// crate and adding one for eight lines of xorshift would be poor value.
struct Rng(u64);

impl Rng {
    fn next_u64(&mut self) -> u64 {
        let mut x = self.0;
        x ^= x << 13;
        x ^= x >> 7;
        x ^= x << 17;
        self.0 = x;
        x
    }
    fn below(&mut self, n: usize) -> usize {
        (self.next_u64() % n.max(1) as u64) as usize
    }
}

/// Representative worksheet XML to mutate.
fn sample_part() -> Vec<u8> {
    let mut s = String::from(
        r#"<?xml version="1.0" encoding="UTF-8"?><worksheet xmlns="http://x"><sheetData>"#,
    );
    for r in 1..=40 {
        s.push_str(&format!(
            "<row r=\"{r}\"><c r=\"A{r}\"><v>{r}</v></c><c r=\"B{r}\" t=\"str\"><v>x{r}</v></c></row>"
        ));
    }
    s.push_str("</sheetData><mergeCells><mergeCell ref=\"A1:B2\"/></mergeCells></worksheet>");
    s.into_bytes()
}

#[test]
fn truncated_inputs_never_panic_and_always_name_the_part() {
    // Property test with a fixed seed: for EVERY truncation point, the scan
    // either completes or returns a named error. It never panics, and it
    // never returns an unnamed error.
    //
    // Truncation points are sampled rather than exhaustive so
    // `cargo test --workspace` stays fast; the seed makes any failure
    // reproducible.
    let base = sample_part();
    let mut rng = Rng(0x5EED_1234_ABCD_0001);
    let mut errored = 0usize;
    for i in 0..400 {
        let cut = rng.below(base.len());
        let input = &base[..cut];
        match scan_part(input, "fuzz.xlsx", "xl/worksheets/sheet1.xml", None, |_| {
            Ok(())
        }) {
            Ok(()) => {}
            Err(e) => {
                errored += 1;
                assert_eq!(
                    e.part(),
                    Some("xl/worksheets/sheet1.xml"),
                    "iteration {i} (seed 0x5EED1234ABCD0001, cut {cut}) produced an error \
                     that does not name the failing part: {e}"
                );
            }
        }
    }
    // If nothing errored, the scanner is accepting truncated XML — which is
    // precisely the bug. Most cuts land mid-element, so this is a real bar.
    assert!(
        errored > 200,
        "only {errored}/400 truncations were detected; a truncated sheet is being \
         accepted as a complete one"
    );
}

#[test]
fn byte_flipped_inputs_never_panic() {
    // The other half: corruption in the middle rather than at the end. The
    // assertion is that we always get a Result — a panic here fails the test
    // by unwinding out of it — and that any error names the part.
    let base = sample_part();
    let mut rng = Rng(0x5EED_1234_ABCD_0002);
    let mut errored = 0usize;
    for i in 0..400 {
        let mut input = base.clone();
        // One to four flipped bytes, so single-byte damage and heavier
        // corruption are both covered.
        for _ in 0..=rng.below(4) {
            let at = rng.below(input.len());
            input[at] ^= (rng.below(255) + 1) as u8;
        }
        match scan_part(
            &input,
            "fuzz.xlsx",
            "xl/worksheets/sheet1.xml",
            None,
            |_| Ok(()),
        ) {
            Ok(()) => {}
            Err(e) => {
                errored += 1;
                assert_eq!(
                    e.part(),
                    Some("xl/worksheets/sheet1.xml"),
                    "iteration {i} (seed 0x5EED1234ABCD0002) produced an unnamed error: {e}"
                );
            }
        }
    }
    assert!(
        errored > 20,
        "only {errored}/400 byte-flipped documents were rejected; corruption is \
         being accepted silently"
    );
}

#[test]
fn random_bytes_never_panic() {
    // Pure noise, including invalid UTF-8. Nothing here should ever panic.
    let mut rng = Rng(0x5EED_1234_ABCD_0003);
    for i in 0..200 {
        let len = rng.below(512);
        let input: Vec<u8> = (0..len).map(|_| rng.below(256) as u8).collect();
        let r = scan_part(&input, "noise.xlsx", "part", None, |_| Ok(()));
        if let Err(e) = r {
            assert!(
                e.part().is_some(),
                "iteration {i}: random input produced an unnamed error: {e}"
            );
        }
    }
}

#[test]
fn a_corrupt_zip_is_an_error_not_a_panic() {
    // Feeding non-zip bytes, and a real zip with its middle overwritten.
    let fx = Fixtures::new("corruptzip");
    let junk = fx.path("junk.xlsx");
    std::fs::write(&junk, b"this is definitely not a zip archive").unwrap();
    let err = open_checked(&junk, &Limits::with_bytes(u64::MAX, u64::MAX))
        .expect_err("non-zip bytes must be refused");
    assert!(
        matches!(err, SafeguardError::PartUnreadable { .. }),
        "{err:?}"
    );

    let real = fx.path("real.xlsx");
    build_zip(&real, &[("xl/workbook.xml", &vec![b'a'; 5000])], true);
    let mut bytes = std::fs::read(&real).unwrap();
    let mid = bytes.len() / 2;
    for b in bytes.iter_mut().skip(mid).take(64) {
        *b ^= 0xFF;
    }
    let damaged = fx.path("damaged.xlsx");
    std::fs::write(&damaged, &bytes).unwrap();
    // Whatever happens, it is a Result. Reaching this line at all is the
    // assertion; a panic inside `zip` would unwind out of the test.
    let _ = open_checked(&damaged, &Limits::with_bytes(u64::MAX, u64::MAX));
}

// -------------------------------------------------------- bounded memory ---

#[test]
fn a_part_over_the_cap_is_refused_naming_the_part() {
    let fx = Fixtures::new("partcap");
    let p = fx.path("big.xlsx");
    build_zip(
        &p,
        &[("xl/worksheets/sheet1.xml", &vec![b'x'; 200_000])],
        false,
    );
    let mut zip = open(&p);
    let limits = Limits::with_bytes(50_000, u64::MAX);
    let err = read_all_parts(&mut zip, "big.xlsx", &limits, None)
        .expect_err("a 200KB part must not fit a 50KB per-part cap");
    let SafeguardError::PartTooLarge { part, declared, .. } = &err else {
        panic!("expected PartTooLarge, got {err:?}");
    };
    assert_eq!(part, "xl/worksheets/sheet1.xml");
    assert_eq!(*declared, 200_000);
}

#[test]
fn crossing_the_running_total_fails_mid_stream_and_keeps_nothing() {
    // The criterion: a file exceeding the memory bound fails cleanly
    // mid-stream with partial state discarded. Three 40KB parts against a
    // 100KB total — the third must fail, and NOTHING may come back.
    let fx = Fixtures::new("total-midstream");
    let p = fx.path("three.xlsx");
    let body = vec![b'x'; 40_000];
    build_zip(
        &p,
        &[("a.xml", &body), ("b.xml", &body), ("c.xml", &body)],
        false,
    );
    let mut zip = open(&p);
    let limits = Limits::with_bytes(u64::MAX, 100_000);
    let err = read_all_parts(&mut zip, "three.xlsx", &limits, None)
        .expect_err("120KB across three parts must not fit a 100KB total");
    let SafeguardError::TotalTooLarge { so_far, limit, .. } = &err else {
        panic!("expected TotalTooLarge, got {err:?}");
    };
    // It must have failed PART WAY THROUGH, not at the first part — that is
    // what "mid-stream" means, and a check that refused everything up front
    // would report so_far == 0.
    assert_eq!(
        *so_far, 80_000,
        "must fail on the third part, not the first"
    );
    assert_eq!(*limit, 100_000);
    // And the return type carries no partial map: `read_all_parts` gives
    // back `Result<HashMap, _>`, so an Err provably discards the 80KB read.
}

#[test]
fn a_lying_size_header_cannot_smuggle_bytes_past_the_cap() {
    // `read_part_capped` enforces the ceiling on bytes ACTUALLY read, so an
    // entry whose header under-declares its content is caught rather than
    // silently truncated into wrong data.
    let src: &[u8] = &vec![b'z'; 5000];
    let err = read_part_capped(src, 1000, "f.xlsx", "xl/sheet.xml")
        .expect_err("a source larger than the cap must be refused");
    let SafeguardError::PartOverran { part, limit, .. } = &err else {
        panic!("expected PartOverran, got {err:?}");
    };
    assert_eq!(part, "xl/sheet.xml");
    assert_eq!(*limit, 1000);

    // Exactly at the limit is fine — an off-by-one here would reject real files.
    let exact: &[u8] = &vec![b'z'; 1000];
    let got = read_part_capped(exact, 1000, "f.xlsx", "p").expect("exactly at the cap must pass");
    assert_eq!(got.len(), 1000);
}

#[test]
fn limits_scale_with_the_measured_budget() {
    // The caps must be derived, not constants — a 2 GB VM and a 128 GB
    // workstation should not get the same per-part ceiling.
    let small = Limits::from_budget(&ferrix_core::Budget::from_available(2 << 30));
    let large = Limits::from_budget(&ferrix_core::Budget::from_available(128 << 30));
    assert!(
        large.max_total_bytes > small.max_total_bytes * 8,
        "limits must track the machine: {} vs {}",
        small.max_total_bytes,
        large.max_total_bytes
    );
    // But never unbounded, however much RAM is reported.
    assert!(large.max_part_bytes <= ABSOLUTE_MAX_PART_BYTES);
}

#[test]
fn too_many_entries_is_refused() {
    let fx = Fixtures::new("entries");
    let p = fx.path("many.xlsx");
    let entries: Vec<(String, Vec<u8>)> =
        (0..50).map(|i| (format!("p{i}.xml"), vec![b'x'])).collect();
    let refs: Vec<(&str, &[u8])> = entries
        .iter()
        .map(|(n, b)| (n.as_str(), b.as_slice()))
        .collect();
    build_zip(&p, &refs, false);
    let mut zip = open(&p);
    let mut limits = Limits::with_bytes(u64::MAX, u64::MAX);
    limits.max_entries = 10;
    let err = inspect_archive(&mut zip, "many.xlsx", &limits).expect_err("50 > 10 entries");
    let SafeguardError::TooManyEntries { count, limit, .. } = &err else {
        panic!("expected TooManyEntries, got {err:?}");
    };
    assert_eq!(*count, 50);
    assert_eq!(*limit, 10);
}

// ---------------------------------------------------------- cancellation ---

#[test]
fn a_cancelled_scan_stops_and_reports_the_part() {
    // The token must be polled often enough to matter, and the refusal must
    // name where it stopped.
    let token = CancelToken::new();
    token.cancel();
    // A part long enough to cross at least one poll boundary.
    let mut xml = String::from("<root>");
    for i in 0..(CANCEL_POLL_EVENTS * 2) {
        xml.push_str(&format!("<c r=\"A{i}\"/>"));
    }
    xml.push_str("</root>");
    let err = scan_part(
        xml.as_bytes(),
        "f.xlsx",
        "xl/worksheets/sheet1.xml",
        Some(&token),
        |_| Ok(()),
    )
    .expect_err("a cancelled scan must stop");
    let SafeguardError::Cancelled { part, .. } = &err else {
        panic!("expected Cancelled, got {err:?}");
    };
    assert_eq!(part, "xl/worksheets/sheet1.xml");
}

#[test]
fn an_uncancelled_scan_of_the_same_input_completes() {
    // Without this control, the test above passes against a scanner that
    // always reports cancellation.
    let token = CancelToken::new();
    let mut xml = String::from("<root>");
    for i in 0..(CANCEL_POLL_EVENTS * 2) {
        xml.push_str(&format!("<c r=\"A{i}\"/>"));
    }
    xml.push_str("</root>");
    let mut seen = 0usize;
    scan_part(xml.as_bytes(), "f.xlsx", "part", Some(&token), |_| {
        seen += 1;
        Ok(())
    })
    .expect("an uncancelled scan must complete");
    assert!(
        seen >= CANCEL_POLL_EVENTS * 2,
        "the whole part must be scanned, saw {seen} events"
    );
}

#[test]
fn cancelling_a_package_read_discards_everything_read_so_far() {
    let fx = Fixtures::new("cancel-parts");
    let p = fx.path("many.xlsx");
    let body = vec![b'x'; 1000];
    build_zip(
        &p,
        &[("a.xml", &body), ("b.xml", &body), ("c.xml", &body)],
        false,
    );
    let token = CancelToken::new();
    token.cancel();
    let mut zip = open(&p);
    let err = read_all_parts(
        &mut zip,
        "many.xlsx",
        &Limits::with_bytes(u64::MAX, u64::MAX),
        Some(&token),
    )
    .expect_err("a cancelled package read must not return parts");
    assert!(matches!(err, SafeguardError::Cancelled { .. }), "{err:?}");

    // The control: the same archive reads fine when not cancelled, so the
    // refusal above is the token's doing and not a broken fixture.
    token.reset();
    let mut zip = open(&p);
    let parts = read_all_parts(
        &mut zip,
        "many.xlsx",
        &Limits::with_bytes(u64::MAX, u64::MAX),
        Some(&token),
    )
    .expect("an uncancelled read must succeed");
    assert_eq!(parts.len(), 3);
}

// -------------------------------------------------------------- cleanup ---

#[test]
fn fixtures_are_removed_when_a_test_ends() {
    // The agent guide requires generated fixtures to be cleaned up. Proven
    // rather than asserted in a comment.
    let dir;
    {
        let fx = Fixtures::new("cleanup");
        dir = fx.0.clone();
        std::fs::write(fx.path("x.bin"), b"data").unwrap();
        assert!(dir.exists());
    }
    assert!(!dir.exists(), "fixture directory must be removed on drop");
}
